development:
  login: "contac_1265281294_biz_api1.gmail.com"
  password: "1265281302"
  signature: "ADE8004A7Jqs3p9ALruQj7GZR1uzAECMzJykpXFsoQdIma4UNaSttF3G"
staging:
  login: "contac_1265281294_biz_api1.gmail.com"
  password: "1265281302"
  signature: "ADE8004A7Jqs3p9ALruQj7GZR1uzAECMzJykpXFsoQdIma4UNaSttF3G"